"""
Data loading module for Solar Production Prediction.
Handles loading and initial preprocessing of generation and weather data.
"""

import pandas as pd
import numpy as np
from pathlib import Path
from typing import Tuple

from .config import PLANT_CONFIG, DATA_PATHS, ML_CONFIG


def _path_exists(path_key: str) -> bool:
    """Return True when a configured data path exists."""
    return Path(DATA_PATHS[path_key]).exists()


def _parse_local_datetime(series: pd.Series) -> pd.Series:
    """Parse timestamps as UTC/local-aware and return Asia/Dhaka timestamps."""
    return pd.to_datetime(series, utc=True, errors='coerce').dt.tz_convert(PLANT_CONFIG['timezone'])


def load_plant_data() -> pd.DataFrame:
    """Load inverter plant configuration data, preferring cleaned local metadata."""
    path = DATA_PATHS['plants_clean'] if _path_exists('plants_clean') else DATA_PATHS['inverter_plants']
    df_plants = pd.read_csv(path)
    df_plants['plant_address'] = df_plants['plant_address'].fillna('Gazipur')
    return df_plants


def load_generation_data(plant_name: str = None) -> pd.DataFrame:
    """
    Load cleaned hourly generation targets, falling back to raw 5-minute aggregation.

    Args:
        plant_name: Name of plant to filter. Defaults to config value.

    Returns:
        DataFrame with hourly generation data
    """
    if plant_name is None:
        plant_name = PLANT_CONFIG['name']

    # Prefer the explicit cleaned hourly modeling target when available. It is
    # generated by build_clean_dataset.py from 5-minute inverter data only.
    if _path_exists('hourly_model_targets'):
        df_hourly = pd.read_csv(DATA_PATHS['hourly_model_targets'])
        df_hourly = df_hourly[df_hourly['plant_name'] == plant_name].copy()
        df_hourly['generation_date'] = _parse_local_datetime(df_hourly['generation_date'])
        df_hourly = df_hourly.sort_values('generation_date').reset_index(drop=True)
        return df_hourly

    # Fallback for setup before clean/ has been built.
    df_plants = load_plant_data()
    df = pd.read_csv(DATA_PATHS['generation_5m'])

    # Merge with plant info
    df['generation_date'] = _parse_local_datetime(df['generation_date'])
    df = df.merge(df_plants[['plant_id', 'plant_name']], on='plant_id', how='left')
    df = df[df['plant_name'] == plant_name].copy()

    # Clean generation values
    df['generation_amount'] = df['generation_amount'].astype(str).str.replace(',', '').astype(float)
    df['generation_kwh'] = df['generation_amount'] / 1000

    # Remove duplicates (keep all historical data - no date filtering)
    df = df.drop_duplicates(subset='generation_date', keep='last').sort_values('generation_date')

    # Resample to hourly while preserving data completeness.
    # Important: a missing hour must remain missing, not become 0 kWh.
    hourly = df.set_index('generation_date').resample('1h')['generation_kwh']
    df_hourly = hourly.agg([
        ('generation_kwh_raw', lambda x: x.sum(min_count=1)),
        ('records_collected', 'count')
    ]).reset_index()

    expected_records = 12  # 12 five-minute intervals per complete hour
    min_completeness = ML_CONFIG.get('min_hourly_completeness_pct', 80)

    df_hourly['expected_records'] = expected_records
    df_hourly['missing_records'] = expected_records - df_hourly['records_collected']
    df_hourly['data_completeness_pct'] = (
        df_hourly['records_collected'] / expected_records * 100
    )
    df_hourly['data_available'] = df_hourly['data_completeness_pct'] >= min_completeness

    # Use NaN as the modeling/dashboard target for incomplete hours so they are
    # not silently treated as zero production.
    df_hourly['generation_kwh'] = df_hourly['generation_kwh_raw'].where(
        df_hourly['data_available']
    )

    return df_hourly


def load_weather_data() -> pd.DataFrame:
    """
    Load and preprocess weather data.

    Returns:
        DataFrame with hourly weather data
    """
    if _path_exists('weather_hourly_clean'):
        weather = pd.read_csv(DATA_PATHS['weather_hourly_clean'])
        weather['generation_date'] = _parse_local_datetime(weather['generation_date'])
        weather_cols = ['generation_date', 'temp', 'visibility', 'rain_1h', 'clouds_all']
        return weather[[col for col in weather_cols if col in weather.columns]]

    weather = pd.read_csv(DATA_PATHS['weather'])

    # Parse datetime
    weather['generation_date'] = _parse_local_datetime(weather['dt_iso'].str.replace(' UTC', '', regex=False))

    # Select relevant columns (optimized set - tested extensively)
    weather_cols = ['generation_date', 'temp', 'visibility', 'rain_1h', 'clouds_all']
    weather = weather[weather_cols]

    # Aggregate to hourly (in case of duplicates)
    weather = weather.groupby('generation_date').mean().reset_index()

    return weather


def interpolate_weather(df: pd.DataFrame) -> pd.DataFrame:
    """
    Interpolate missing weather values.

    Args:
        df: DataFrame with weather columns

    Returns:
        DataFrame with interpolated values
    """
    weather_features = ['temp', 'visibility', 'clouds_all']

    for feat in weather_features:
        if feat in df.columns:
            df[feat] = df[feat].interpolate(method='linear', limit_direction='both')

    # Rain is special - fill with 0
    if 'rain_1h' in df.columns:
        df['rain_1h'] = df['rain_1h'].fillna(0)

    return df


def filter_source_agreement_days(df: pd.DataFrame, plant_name: str = None) -> pd.DataFrame:
    """Exclude plant-days where daily inverter validation strongly disagrees.

    This is a training/evaluation filter only. It does not fill hourly gaps or
    change dashboard history; it removes days whose daily inverter control is
    more than the configured tolerance away from the cleaned 5-minute target.
    """
    if plant_name is None:
        plant_name = PLANT_CONFIG['name']

    if not ML_CONFIG.get('source_agreement_training_filter', False):
        return df

    agreement_path = Path(DATA_PATHS['daily_source_agreement'])
    if not agreement_path.exists() or df.empty:
        return df

    agreement = pd.read_csv(agreement_path)
    required_cols = {'plant_name', 'date', 'five_min_kwh', 'daily_inverter_kwh_ratio_to_5min'}
    if not required_cols.issubset(agreement.columns):
        return df

    plant_agreement = agreement[agreement['plant_name'] == plant_name].copy()
    if plant_agreement.empty:
        return df

    ratio = pd.to_numeric(plant_agreement['daily_inverter_kwh_ratio_to_5min'], errors='coerce')
    five_min_kwh = pd.to_numeric(plant_agreement['five_min_kwh'], errors='coerce')
    plant_thresholds = ML_CONFIG.get('max_daily_inverter_ratio_difference_by_plant', {})
    max_difference = plant_thresholds.get(
        plant_name,
        ML_CONFIG.get('max_daily_inverter_ratio_difference', 1.00)
    )
    min_daily_kwh = ML_CONFIG.get('min_daily_kwh_for_agreement_filter', 1.0)

    weak_mask = (
        ratio.notna()
        & five_min_kwh.notna()
        & (five_min_kwh >= min_daily_kwh)
        & ((ratio - 1).abs() > max_difference)
    )
    weak_dates = set(pd.to_datetime(plant_agreement.loc[weak_mask, 'date']).dt.date)
    if not weak_dates:
        return df

    before = len(df)
    df = df.copy()
    df['_source_agreement_date'] = pd.to_datetime(df['generation_date']).dt.date
    df = df[~df['_source_agreement_date'].isin(weak_dates)].drop(columns='_source_agreement_date')
    removed = before - len(df)
    print(
        f"  ✓ Source-agreement filter removed {removed:,} rows across {len(weak_dates)} weak days "
        f"for {plant_name}"
    )
    return df.reset_index(drop=True)


def merge_generation_weather(
    df_generation: pd.DataFrame,
    df_weather: pd.DataFrame
) -> pd.DataFrame:
    """
    Merge generation and weather data on timestamp.

    Args:
        df_generation: Hourly generation data
        df_weather: Hourly weather data

    Returns:
        Merged DataFrame
    """
    df = df_generation.merge(df_weather, on='generation_date', how='left')
    df = interpolate_weather(df)
    return df


def load_complete_dataset() -> pd.DataFrame:
    """
    Load complete dataset with generation and weather data.
    This is the main function to use for data loading.

    Returns:
        DataFrame with all data ready for feature engineering
    """
    print("📊 Loading complete dataset...")

    # Load generation data
    df_generation = load_generation_data()
    print(f"  ✓ {len(df_generation):,} hourly generation records loaded")

    # Load weather data
    df_weather = load_weather_data()
    print(f"  ✓ Weather data loaded")

    # Merge
    df = merge_generation_weather(df_generation, df_weather)
    print(f"  ✓ Data merged")

    return df


def split_train_test(
    df: pd.DataFrame,
    plant_name: str = None,
    split_date: str = None,
    target_col: str = 'generation_kwh'
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    Split data into train and test sets using hybrid approach with priority system.

    Priority 1: Use explicit split_date if provided
    Priority 2: Use plant-specific date from config if plant_name is in config
    Priority 3: Use relative duration (last N months as test)
    Priority 4: Use percentage fallback if not enough data for relative duration

    Args:
        df: Complete dataset
        plant_name: Name of plant (for plant-specific split dates)
        split_date: Explicit date to split on (YYYY-MM-DD). Overrides all other methods.
        target_col: Name of target column

    Returns:
        Tuple of (train_df, test_df)
    """
    from .config import ML_CONFIG

    if plant_name is None:
        plant_name = PLANT_CONFIG['name']

    latest_date = df['generation_date'].max()

    # Priority 1: Explicit split_date provided
    if split_date is not None:
        split_ts = pd.Timestamp(split_date)
        if split_ts.tz is None:
            split_ts = split_ts.tz_localize(PLANT_CONFIG['timezone'])
        print(f"✓ Using explicit split date: {split_ts.date()}")

    # Priority 2: Plant-specific date from config
    elif plant_name in ML_CONFIG['plant_split_dates']:
        split_date_str = ML_CONFIG['plant_split_dates'][plant_name]
        split_ts = pd.Timestamp(split_date_str).tz_localize(PLANT_CONFIG['timezone'])
        print(f"✓ Using plant-specific split date for '{plant_name}': {split_ts.date()}")

    # Priority 3: Relative duration (last N months as test)
    else:
        split_ts = latest_date - pd.DateOffset(months=ML_CONFIG['test_months'])
        print(f"✓ Using relative split date: {split_ts.date()} ({ML_CONFIG['test_months']} months before latest)")

    # Verify enough test samples
    test_df_temp = df[df['generation_date'] >= split_ts].copy()

    # Priority 4: Fallback to percentage if not enough test samples
    if len(test_df_temp) < ML_CONFIG['min_test_samples']:
        print(f"⚠️  Warning: Only {len(test_df_temp)} test samples (minimum: {ML_CONFIG['min_test_samples']})")
        print(f"⚠️  Falling back to {ML_CONFIG['train_test_ratio']*100:.0f}% train/test split")

        split_idx = int(len(df) * ML_CONFIG['train_test_ratio'])
        split_ts = df.iloc[split_idx]['generation_date']
        print(f"✓ New split date: {split_ts.date()}")

    # Perform the split
    train_df = df[df['generation_date'] < split_ts].copy()
    test_df = df[df['generation_date'] >= split_ts].copy()

    # Display summary
    print(f"\n📊 Train/Test Split Summary:")
    print(f"  Training:   {len(train_df):,} samples ({train_df['generation_date'].min().date()} to {train_df['generation_date'].max().date()})")
    print(f"  Test:       {len(test_df):,} samples ({test_df['generation_date'].min().date()} to {test_df['generation_date'].max().date()})")
    print(f"  Split Ratio: {len(train_df)/len(df)*100:.1f}% train / {len(test_df)/len(df)*100:.1f}% test")

    return train_df, test_df
